#!/bin/bash
source /etc/eCrimeLabs/eCrimeLabscfg

ENGINE=`grep ENGINE /etc/nsm/securityonion.conf | cut -d= -f2`

# Run download script
/usr/sbin/download-eCrimeLabs

echo ""
echo "Configuring Pulledpork..."
echo ""

PP_CONF="/etc/nsm/pulledpork/pulledpork.conf"

if [ "${ENGINE}" = "snort" ]; then
	sed -i "s|^local_rules.*|local_rules=/etc/nsm/rules/local.rules,${RULE_PATH_FEED},${RULE_PATH_INCIDENT}|" ${PP_CONF}
elif [ "${ENGINE}" = "suricata" ];then
	sed -i "s|^local_rules.*|local_rules=/etc/nsm/rules/local.rules,/etc/nsm/rules/decoder-events.rules,/etc/nsm/rules/stream-events.rules,/etc/nsm/rules/http-events.rules,/etc/nsm/rules/smtp-events.rules,${RULE_PATH_FEED},${RULE_PATH_INCIDENT}|" ${PP_CONF}
fi

if [ -f /etc/cron.d/download-eCrimeLabs ]; then
	:
else
	touch /etc/cron.d/download-eCrimeLabs
	cat << EOF > /etc/cron.d/download-eCrimeLabs
# /etc/cron.d/download-eCrimeLabs
#
# crontab entry to update eCrimeLabs IDS rules

SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

#m 		h 	dom 	mon 	dow 	user  command
15 		* 	* 		* 		*   	root	/usr/sbin/download-eCrimeLabs > /dev/null 2>&1
EOF
fi

echo "If manually running this script, ensure that /usr/sbin/rule-update is run afterwards."

echo ""
echo "That's all folks!"
echo ""
